import json


def update_oracle_json():
    json_path = "c:/rentawallstreet/tests/oracle_generator/irpf_oracle_tests.json"
    with open(json_path, "r", encoding="utf-8") as f:
        cases = json.load(f)

    # Mapeo de resultados reales extraídos (Estructura Extendida 25 campos)
    real_data = {
        "SAL-MAD-17K": {
            "resultado_declaracion": -635.03,
            "base_imponible_general": 8448.97,
            "base_liquidable_general_gravamen": 8448.97,
            "base_imponible_ahorro": 0.0,
            "base_liquidable_ahorro": 0.0,
            "minimo_personal_familiar_estatal": 5550.0,
            "minimo_personal_familiar_autonomico": 5790.0,
            "cuota_integra_estatal": 275.40,
            "cuota_integra_autonomica": 856.92,
            "suma_deducciones_autonomicas": 0.0,
            "cuota_liquida_estatal": 0.0,
            "cuota_liquida_autonomica": 0.0,
            "cuota_liquida_estatal_incrementada": 0.0,
            "cuota_liquida_autonomica_incrementada": 0.0,
            "cuota_liquida_incrementada_total": 0.0,
            "cuota_resultante_autoliquidacion": 0.0,
            "retenciones_pagos_cuenta": 1767.35,
            "cuota_diferencial": -635.03,
            "deduccion_maternidad": 0.0,
            "deduccion_maternidad_guarderia": 0.0,
            "deduccion_descendientes_discapacidad": 0.0,
            "deduccion_ascendientes_discapacidad": 0.0,
            "deduccion_conyuge_discapacidad": 0.0,
            "deduccion_familia_numerosa": 0.0,
            "deduccion_ascendiente_2_hijos": 0.0,
        },
        "SAL-AND-2K": {
            "resultado_declaracion": -40.0,
            "base_imponible_general": 0.0,
            "base_liquidable_general_gravamen": 0.0,
            "base_imponible_ahorro": 0.0,
            "base_liquidable_ahorro": 0.0,
            "minimo_personal_familiar_estatal": 5550.0,
            "minimo_personal_familiar_autonomico": 5790.0,
            "cuota_integra_estatal": 0.0,
            "cuota_integra_autonomica": 0.0,
            "suma_deducciones_autonomicas": 0.0,
            "cuota_liquida_estatal": 0.0,
            "cuota_liquida_autonomica": 0.0,
            "cuota_liquida_estatal_incrementada": 0.0,
            "cuota_liquida_autonomica_incrementada": 0.0,
            "cuota_liquida_incrementada_total": 0.0,
            "cuota_resultante_autoliquidacion": 0.0,
            "retenciones_pagos_cuenta": 40.0,
            "cuota_diferencial": -40.0,
            "deduccion_maternidad": 0.0,
            "deduccion_maternidad_guarderia": 0.0,
            "deduccion_descendientes_discapacidad": 0.0,
            "deduccion_ascendientes_discapacidad": 0.0,
            "deduccion_conyuge_discapacidad": 0.0,
            "deduccion_familia_numerosa": 0.0,
            "deduccion_ascendiente_2_hijos": 0.0,
        },
        "SAL-AND-14K": {
            "resultado_declaracion": -297.04,
            "base_imponible_general": 0.0,
            "base_liquidable_general_gravamen": 0.0,
            "base_imponible_ahorro": 0.0,
            "base_liquidable_ahorro": 0.0,
            "minimo_personal_familiar_estatal": 5550.0,
            "minimo_personal_familiar_autonomico": 5790.0,
            "cuota_integra_estatal": 0.0,
            "cuota_integra_autonomica": 0.0,
            "suma_deducciones_autonomicas": 0.0,
            "cuota_liquida_estatal": 0.0,
            "cuota_liquida_autonomica": 0.0,
            "cuota_liquida_estatal_incrementada": 0.0,
            "cuota_liquida_autonomica_incrementada": 0.0,
            "cuota_liquida_incrementada_total": 0.0,
            "cuota_resultante_autoliquidacion": 0.0,
            "retenciones_pagos_cuenta": 297.04,
            "cuota_diferencial": -297.04,
            "deduccion_maternidad": 0.0,
            "deduccion_maternidad_guarderia": 0.0,
            "deduccion_descendientes_discapacidad": 0.0,
            "deduccion_ascendientes_discapacidad": 0.0,
            "deduccion_conyuge_discapacidad": 0.0,
            "deduccion_familia_numerosa": 0.0,
            "deduccion_ascendiente_2_hijos": 0.0,
        },
        "SAL-AND-17K": {
            "resultado_declaracion": -902.29,
            "base_imponible_general": 10222.94,
            "base_liquidable_general_gravamen": 10222.94,
            "base_imponible_ahorro": 0.0,
            "base_liquidable_ahorro": 0.0,
            "minimo_personal_familiar_estatal": 5550.0,
            "minimo_personal_familiar_autonomico": 5790.0,
            "cuota_integra_estatal": 443.93,
            "cuota_integra_autonomica": 421.13,
            "suma_deducciones_autonomicas": 0.0,
            "cuota_liquida_estatal": 443.93,
            "cuota_liquida_autonomica": 421.13,
            "cuota_liquida_estatal_incrementada": 443.93,
            "cuota_liquida_autonomica_incrementada": 421.13,
            "cuota_liquida_incrementada_total": 865.06,
            "cuota_resultante_autoliquidacion": 865.06,
            "retenciones_pagos_cuenta": 1767.35,
            "cuota_diferencial": -902.29,
            "deduccion_maternidad": 0.0,
            "deduccion_maternidad_guarderia": 0.0,
            "deduccion_descendientes_discapacidad": 0.0,
            "deduccion_ascendientes_discapacidad": 0.0,
            "deduccion_conyuge_discapacidad": 0.0,
            "deduccion_familia_numerosa": 0.0,
            "deduccion_ascendiente_2_hijos": 0.0,
        },
        "SAL-AND-19K": {
            "resultado_declaracion": -72.94,
            "base_imponible_general": 12296.92,
            "base_liquidable_general_gravamen": 12296.92,
            "base_imponible_ahorro": 0.0,
            "base_liquidable_ahorro": 0.0,
            "minimo_personal_familiar_estatal": 5550.0,
            "minimo_personal_familiar_autonomico": 5790.0,
            "cuota_integra_estatal": 969.18,
            "cuota_integra_autonomica": 932.63,
            "suma_deducciones_autonomicas": 0.0,
            "cuota_liquida_estatal": 969.18,
            "cuota_liquida_autonomica": 932.63,
            "cuota_liquida_estatal_incrementada": 969.18,
            "cuota_liquida_autonomica_incrementada": 932.63,
            "cuota_liquida_incrementada_total": 1901.81,
            "cuota_resultante_autoliquidacion": 1901.81,
            "retenciones_pagos_cuenta": 1974.75,
            "cuota_diferencial": -72.94,
            "deduccion_maternidad": 0.0,
            "deduccion_maternidad_guarderia": 0.0,
            "deduccion_descendientes_discapacidad": 0.0,
            "deduccion_ascendientes_discapacidad": 0.0,
            "deduccion_conyuge_discapacidad": 0.0,
            "deduccion_familia_numerosa": 0.0,
            "deduccion_ascendiente_2_hijos": 0.0,
        },
        "SAL-AND-22K": {
            "resultado_declaracion": -548.83,
            "base_imponible_general": 18603.00,
            "base_liquidable_general_gravamen": 18603.00,
            "base_imponible_ahorro": 0.0,
            "base_liquidable_ahorro": 0.0,
            "minimo_personal_familiar_estatal": 5550.0,
            "minimo_personal_familiar_autonomico": 5790.0,
            "cuota_integra_estatal": 1391.23,
            "cuota_integra_autonomica": 1359.94,
            "suma_deducciones_autonomicas": 0.0,
            "cuota_liquida_estatal": 1391.23,
            "cuota_liquida_autonomica": 1359.94,
            "cuota_liquida_estatal_incrementada": 1391.23,
            "cuota_liquida_autonomica_incrementada": 1359.94,
            "cuota_liquida_incrementada_total": 2751.17,
            "cuota_resultante_autoliquidacion": 2751.17,
            "retenciones_pagos_cuenta": 3300.00,
            "cuota_diferencial": -548.83,
            "deduccion_maternidad": 0.0,
            "deduccion_maternidad_guarderia": 0.0,
            "deduccion_descendientes_discapacidad": 0.0,
            "deduccion_ascendientes_discapacidad": 0.0,
            "deduccion_conyuge_discapacidad": 0.0,
            "deduccion_familia_numerosa": 0.0,
            "deduccion_ascendiente_2_hijos": 0.0,
        },
        "SAL-AND-60K": {
            "resultado_declaracion": -6366.25,
            "base_imponible_general": 54190.00,
            "base_liquidable_general_gravamen": 54190.00,
            "base_imponible_ahorro": 0.0,
            "base_liquidable_ahorro": 0.0,
            "minimo_personal_familiar_estatal": 5550.0,
            "minimo_personal_familiar_autonomico": 5790.0,
            "cuota_integra_estatal": 7348.65,
            "cuota_integra_autonomica": 7285.10,
            "suma_deducciones_autonomicas": 0.0,
            "cuota_liquida_estatal": 7348.65,
            "cuota_liquida_autonomica": 7285.10,
            "cuota_liquida_estatal_incrementada": 7348.65,
            "cuota_liquida_autonomica_incrementada": 7285.10,
            "cuota_liquida_incrementada_total": 14633.75,
            "cuota_resultante_autoliquidacion": 14633.75,
            "retenciones_pagos_cuenta": 21000.00,
            "cuota_diferencial": -6366.25,
            "deduccion_maternidad": 0.0,
            "deduccion_maternidad_guarderia": 0.0,
            "deduccion_descendientes_discapacidad": 0.0,
            "deduccion_ascendientes_discapacidad": 0.0,
            "deduccion_conyuge_discapacidad": 0.0,
            "deduccion_familia_numerosa": 0.0,
            "deduccion_ascendiente_2_hijos": 0.0,
        },
        "SAL-AND-300K": {
            "resultado_declaracion": 16993.45,
            "base_imponible_general": 293800.00,
            "base_liquidable_general_gravamen": 293800.00,
            "base_imponible_ahorro": 0.0,
            "base_liquidable_ahorro": 0.0,
            "minimo_personal_familiar_estatal": 5550.0,
            "minimo_personal_familiar_autonomico": 5790.0,
            "cuota_integra_estatal": 60592.56,
            "cuota_integra_autonomica": 61400.89,
            "suma_deducciones_autonomicas": 0.0,
            "cuota_liquida_estatal": 60592.56,
            "cuota_liquida_autonomica": 61400.89,
            "cuota_liquida_estatal_incrementada": 60592.56,
            "cuota_liquida_autonomica_incrementada": 61400.89,
            "cuota_liquida_incrementada_total": 121993.45,
            "cuota_resultante_autoliquidacion": 121993.45,
            "retenciones_pagos_cuenta": 105000.00,
            "cuota_diferencial": 16993.45,
            "deduccion_maternidad": 0.0,
            "deduccion_maternidad_guarderia": 0.0,
            "deduccion_descendientes_discapacidad": 0.0,
            "deduccion_ascendientes_discapacidad": 0.0,
            "deduccion_conyuge_discapacidad": 0.0,
            "deduccion_familia_numerosa": 0.0,
            "deduccion_ascendiente_2_hijos": 0.0,
        },
        # Añadir más casos aquí con la misma estructura
    }

    updated_count = 0
    for case in cases:
        if case["name"] in real_data:
            case["expected_results"].update(real_data[case["name"]])
            updated_count += 1

    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(cases, f, indent=2, ensure_ascii=False)

    print(f"Actualizados {updated_count} casos con esquema extendido en el Oráculo.")


if __name__ == "__main__":
    update_oracle_json()
